### ISSUE TITLE
[Crash Report] Crash when you reach the world height limit

### ISSUE THREAD

**Issue by zlainsama** [Darkhax-Minecraft/Waila-Inhibitors#1]
Crash Report: http://pastebin.com/bM7yEyTc
Ways to reproduce: Fly (creative or other items) to the world height limit (256) while you pointing your view up.
Versions: 1.7.10-forge1448, Waila-1.5.10_1.7.10, Wawla-1.3.1-1.7.10, WailaEvents-1.0.0, Waila Inhib-1.0.0

Now my character is stuck on the sky. I need to remove the mod from my client and server.
Edit: Optifine and Fastcraft is present.

**Comment by Darkhax** [comment]
Thank you for creating this issue, I never would have found this out if you didn't report this to me. Updates will be released soon.
