### ISSUE TITLE
Doesn't work fine with GregTech

### ISSUE THREAD

**Issue by PalePyth** [Darkhax-Minecraft/Waila-Inhibitors#3]
**All** ores look like this:
http://puu.sh/mBrwT/29aaad147e.jpg
http://puu.sh/mBryV/e4c2b54b6b.jpg
http://puu.sh/mBrzq/8e8978cd34.jpg
That's all.
GregTech 5.

**Comment by Darkhax** [comment]
I am not sure what is wrong here. Waila Inhibitors does not make an attempt to hide ores.
