### ISSUE TITLE
Light Issues and Creative Mode

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Darkhax-Minecraft/Waila-Inhibitors#4]
The Light Level detection is still enabled even if the player has the night vision effect, and creative players do not bypass their waila getting shut off.  Not entirely sure if you're still willing to update this mod since it hasn't been touched in 8 months, but those minor fixes would be nice.  
Also, there is still the issue that in daylight, being under a tree shuts off waila.

**Comment by Darkhax** [comment]
lol what
